export const IPC_CHANNELS = {
  AUTH_GET_SESSION: "auth:get-session",
  AUTH_GET_PROVIDERS: "auth:get-providers",
  AUTH_GET_REGIONS: "auth:get-regions",
  AUTH_LOGIN: "auth:login",
  AUTH_LOGOUT: "auth:logout",
  PING_REGIONS: "gfn:ping-regions",
  SUBSCRIPTION_FETCH: "subscription:fetch",
  GAMES_FETCH_MAIN: "games:fetch-main",
  GAMES_FETCH_LIBRARY: "games:fetch-library",
  GAMES_FETCH_PUBLIC: "games:fetch-public",
  GAMES_RESOLVE_LAUNCH_ID: "games:resolve-launch-id",
  CREATE_SESSION: "gfn:create-session",
  POLL_SESSION: "gfn:poll-session",
  REPORT_SESSION_AD: "gfn:report-session-ad",
  STOP_SESSION: "gfn:stop-session",
  GET_ACTIVE_SESSIONS: "gfn:get-active-sessions",
  CLAIM_SESSION: "gfn:claim-session",
  SESSION_CONFLICT_DIALOG: "gfn:session-conflict-dialog",
  CONNECT_SIGNALING: "gfn:connect-signaling",
  DISCONNECT_SIGNALING: "gfn:disconnect-signaling",
  SEND_ANSWER: "gfn:send-answer",
  SEND_ICE_CANDIDATE: "gfn:send-ice-candidate",
  REQUEST_KEYFRAME: "gfn:request-keyframe",
  SIGNALING_EVENT: "gfn:signaling-event",
  TOGGLE_FULLSCREEN: "window:toggle-fullscreen",
  SET_FULLSCREEN: "window:set-fullscreen",
  TOGGLE_POINTER_LOCK: "window:toggle-pointer-lock",
  QUIT_APP: "app:quit",
  SETTINGS_GET: "settings:get",
  SETTINGS_SET: "settings:set",
  SETTINGS_RESET: "settings:reset",
  MICROPHONE_PERMISSION_GET: "microphone:permission:get",
  LOGS_EXPORT: "logs:export",
  LOGS_GET_RENDERER: "logs:get-renderer",
  SCREENSHOT_SAVE: "screenshot:save",
  SCREENSHOT_LIST: "screenshot:list",
  SCREENSHOT_DELETE: "screenshot:delete",
  SCREENSHOT_SAVE_AS: "screenshot:save-as",
  RECORDING_BEGIN: "recording:begin",
  RECORDING_CHUNK: "recording:chunk",
  RECORDING_FINISH: "recording:finish",
  RECORDING_ABORT: "recording:abort",
  RECORDING_LIST: "recording:list",
  RECORDING_DELETE: "recording:delete",
  RECORDING_SHOW_IN_FOLDER: "recording:showInFolder",
  CACHE_REFRESH_MANUAL: "cache:refresh-manual",
  CACHE_STATUS_UPDATE: "cache:status-update",
  CACHE_DELETE_ALL: "cache:delete-all",
  COMMUNITY_GET_THANKS: "community:get-thanks",
  // Media browsing
  MEDIA_LIST_BY_GAME: "media:list-by-game",
  MEDIA_THUMBNAIL: "media:thumbnail",
  MEDIA_SHOW_IN_FOLDER: "media:show-in-folder",
  // PrintedWaste queue integration
  PRINTEDWASTE_QUEUE_FETCH: "printedwaste:queue-fetch",
  PRINTEDWASTE_SERVER_MAPPING_FETCH: "printedwaste:server-mapping-fetch",
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
